### ISSUE TITLE
Open and close position with API

### ISSUE THREAD

**Issue by StebsV2** [ig-python/ig-markets-api-python-library#181] opened 2020-12-17 20:44 UTC
'm trying using API and i want open a position.

I'm following the Documentation and i'm in

https://labs.ig.com/rest-trading-api-reference/service-detail?id=542

I'm using POST request but i understand some params like:

 currencyCode,dealReferenc, expiry, level orderType,quoteID,timeInForce,trilingStop and trilingStopIncrement

Yes, are practically all params. Can someone explain better me what do this params? Or can someone do a example request and them i try to understand all this.

Thank you and sorry for my bad english

**Comment by RRMXkun** [comment] 2020-12-18 11:34
This is what I use to open a Spread Betting BUY position:

```
create_open_position(currency_code='GBP', direction='BUY', epic='CS.D.GBPJPY.TODAY.IP',
                                                             expiry='DFB', force_open='true', guaranteed_stop='false',
                                                             level='', limit_distance=str(round(limit_distance, 2)), limit_level=None,
                                                             order_type='MARKET', quote_id=None, size=str(round(size, 2)),                                                                                                                           stop_distance=str(round(stop_distance, 2)),
                                                             stop_level=None, trailing_stop='false', trailing_stop_increment=None)
```
for a market order. LIMIT orders will be a bit different in that you will have to specify the level.

**Comment by StebsV2** [comment] 2021-01-03 01:47
First of all, HAPPY NEW YEAR @RRMXkun 
I try that 
`limit_distance=10
stop_distance=10
ig_service.create_open_position(
    currency_code='USD',
    direction='BUY', 
    epic='CS.D.BITCOIN.CFD.IP',
    expiry='DFB', 
    force_open='true', 
    guaranteed_stop='false',
    level='',
    limit_distance=str(round(limit_distance, 2)), 
    limit_level=None,
    order_type='MARKET', 
    quote_id=None, 
    size=str(round(0.01, 2)),                                                                                                                           stop_distance=str(round(stop_distance, 2)),
    stop_level=None,
    trailing_stop='false', 
    trailing_stop_increment=None)`
But when i execute i recive this
`{'affectedDeals': [],
 'date': '2021-01-03T01:40:10.727',
 'dealId': 'DIAAAAEV3SKLEBD',
 'dealReference': 'XS5YTH7XU4CTYPT',
 'dealStatus': 'REJECTED',
 'direction': 'BUY',
 'epic': 'CS.D.BITCOIN.CFD.IP',
 'expiry': None,
 'guaranteedStop': False,
 'level': None,
 'limitDistance': None,
 'limitLevel': None,
 'profit': None,
 'profitCurrency': None,
 'reason': 'REJECT_SPREADBET_ORDER_ON_CFD_ACCOUNT',
 'size': None,
 'status': None,
 'stopDistance': None,
 'stopLevel': None,
 'trailingStop': False}`
When i go on browser to see position it is not open.
I don't understand how to buy and sell without create that and if u can explain me what is Expiry and this limit and stop distance

**Comment by RRMXkun** [comment] 2021-01-11 18:05
Happy new year to you. For CFD, expiry needs to be set to '-' rather then DFB. Limit and stop distance you need to determine yourself, but it is the distance (in points) from the price level. For example if you buy a price of at £1,000, with £1 per point, if you set the limit distance to 50, the profit limit will be set at £1,050. Same for stop loss.

**Comment by byod0** [comment] 2021-01-18 08:31
@StebsV2  after your tests can you reply to continue or close issues.
There many issues open at this time.

**Comment by jackyclever** [comment] 2021-02-09 06:55
Hi all, I have a similar issue:

closeOrder = ig_service.close_open_position(deal_id=DIAAAAE54P3YPAQ, direction="BUY", epic=epic1, expiry="-",
                                            level=None, order_type="MARKET", quote_id=None, size=50)

I have this error: IGException: {"errorCode":"validation.mutual-exclusive-value.request"}

not sure what went wrong? any suggestion will be appreciated.

**Comment by byod0** [comment] 2021-02-09 07:22
If you try to close BUY,  put SELL in order params.

Le mar. 9 févr. 2021 à 07:55, jackyclever <notifications@github.com> a
écrit :

**Comment by jackyclever** [comment] 2021-02-09 07:48
thank you Byod0, i have put the opposite, it was a "SELL" order, (short), therefore the direction I put is "BUY".
thinking if it was "SELL" order, it might not be "MARKET" AS order_type?

**Comment by byod0** [comment] 2021-02-09 10:07
Have your try it on demo account ? 
i have build partial out application, i have this in my code. 
>
```
    def get_inv_direction(self, direction):
        if direction == 'BUY':
            return 'SELL'
        elif direction == 'SELL':
            return 'BUY'
        else:
            return False

                    ayam.ig_service.close_open_position(deal_id=all_p['position']['dealId'],
                                                        direction=self.get_inv_direction(all_p['position']['direction']),
                                                        epic=None,
                                                        expiry=None,
                                                        level=None,
                                                        order_type="MARKET",
                                                        quote_id=None,
                                                        size=str(size_to_cut),
                                                        session=None)
                    
```

**Comment by jackyclever** [comment] 2021-02-09 21:37
Hi byod0, i have this code, the same as yours:

closeOrder = ig_service.close_open_position(deal_id="DIAAAAE54P3YPAQ", direction="BUY", epic="AB.D.ZMLAU.CASH.IP", 
                                            expiry=None,level=None, order_type="MARKET", quote_id=None, 
                                            size=str(50), session=None)

trying to close a "SELL" orer. still have this error:

IGException: {"errorCode":"validation.mutual-exclusive-value.request"}

any other suggestions?

**Comment by byod0** [comment] 2021-02-09 22:09
Check hère.
https://labs.ig.com/rest-trading-api-reference/service-detail?id=542

I don t meet your market.
Check close as  market IS possible ? Its not possible for BINARY market.

Le mar. 9 févr. 2021 à 22:38, jackyclever <notifications@github.com> a
écrit :

**Comment by byod0** [comment] 2021-02-09 22:13
Have you try with companion if market interface ?
https://labs.ig.com/sample-apps/api-companion/index.html

**Comment by jackyclever** [comment] 2021-02-09 22:36
Hi byod0, yes, have tried the companion, but i have the same error. :(

this is the sell/short order, as "market":

shortOrder = ig_service.create_open_position(currency_code="AUD", direction="SELL", epic=epic1, expiry="-",
                                            force_open="true", guaranteed_stop="false", level=None, 
                                            limit_distance=None, limit_level=None, order_type="MARKET", quote_id=None, 
                                            size=50, stop_distance=None, stop_level=None, trailing_stop=None, 
                                            trailing_stop_increment=None)

now, i cannot close this deal id:

closeOrder = ig_service.close_open_position(deal_id="DIAAAAE54P3YPAQ", direction="BUY", epic="AB.D.ZMLAU.CASH.IP",
expiry=None,level=None, order_type="MARKET", quote_id=None,
size=str(50), session=None)

**Comment by byod0** [comment] 2021-02-09 23:00
If you cannot close with companion interface. Error not provide from github
code...
Tomorrow i try to open position on same Epic, ans i try to close on m'y
demo account.

Le mar. 9 févr. 2021 à 23:37, jackyclever <notifications@github.com> a
écrit :

**Comment by jackyclever** [comment] 2021-02-10 00:18
very appreciate it! thank you byod0

**Comment by jackyclever** [comment] 2021-02-12 00:50
Hi byod0, I have found the solution, when closing an open position, we dont need to specify the epic:

closeOrder = ig_service.close_open_position(deal_id=deal_id, direction="BUY" if direction=="SELL" else "SELL",
                                                    epic=None, expiry=None, level=None, order_type="MARKET", quote_id=None,
                                                    size=f'{size}', session=None)

set epic = None.

problem resolved.

**Comment by byod0** [comment] 2021-02-12 07:10
Ah simple.... There is not Epic in my exemple.!

**Comment by byod0** [comment] 2021-02-12 07:10
You can cancel or close issue

**Comment by jackyclever** [comment] 2021-02-12 22:23
thank you byod0, but I am not the one open this thread, i cannot close it.

**Comment by leoeduardo** [comment] 2021-02-22 15:59
Hi all,
I bought a new computer and Installed everything. Then my 'normal trading Codes' do not work. The issue is  at trailing_stop and trailing_stop_increment.
I realized that I was always using trading_ig==0.0.6 

Now with Version 0.0.8 I have the error:

`"errorCode":"validation.target-value-conditional-set-value.request"`

I tried manag combination of values likes

trailing_stop='false' or 'False' or None also with numerical values and still getting the same error.

Does anyone knows something?  I also test it on trading_ig==0.0.7 

Thanks in Advance

**Comment by RRMXkun** [comment] 2021-02-25 20:30
@leoeduardo can you posy your full call to the method please so we can see all the parameters you're passing?

**Comment by leoeduardo** [comment] 2021-02-26 10:50
Hi here is what I have done for trading_ig==0.0.6 with no problem

`currency_code="JPY"
epic="CS.D."+"AUDJPY"+".MINI.IP"
direction='BUY' #'BUY' or 'SELL'
instrument="AUDJPY"
expiry='-'
force_open=False #if true a new order will not cancel out existing one; has to be true for any LIMIT order type
guaranteed_stop=False
level=None #specify only when orderType = LIMIT
limit_distance=None #close when profit exceeds limitDistance points or pips
limit_level=83.3
order_type='MARKET' #'LIMIT' or 'MARKET' or STOP_ORDER
quote_id=None
size=1
trailing_stop=None
trailing_stop_increment=None
stop_distance=None #close when loss exceeds stopDistance points /pips
stop_level=82.8

open_position = ig_service.create_open_position(currency_code=currency_code,
                                                epic=epic,
                                                direction=direction,
                                                expiry=expiry,
                                                force_open=force_open,
                                                guaranteed_stop=guaranteed_stop,
                                                level=level,
                                                limit_distance=limit_distance,
                                                limit_level=limit_level,
                                                order_type=order_type,
                                                quote_id=quote_id,
                                                size=size,
                                                stop_distance=stop_distance,
                                                stop_level=stop_level,
                                                )`

for new version I got the issue of adding the values trailing_stop and trailing_stop_increment.
I  used different combination of their values like:
`trailing_stop = None
trailing_stop_increment = None

or 

trailing_stop = False
trailing_stop_increment = False

or 

trailing_stop = "false"
trailing_stop_increment = None

etc, etc etc

`
and still having the same  error:

`errorCode":"validation.target-value-conditional-set-value.request`

Thanks in advance for your help

**Comment by bug-or-feature** [comment] 2021-07-06 07:58
Closing this as the original issue is resolved.

@leoeduardo please create a new issue

**Closed by bug-or-feature** 2021-07-06 07:58 UTC
