### ISSUE TITLE
ImportError: cannot import name 'munchify' from 'trading_ig.utils' 

### ISSUE THREAD

**Issue by wailam2323** [ig-python/ig-markets-api-python-library#240] opened 2021-12-21 17:58 UTC
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-1dd42b996d54> in <module>
----> 1 from trading_ig import IGService
      2 from trading_ig.config import config
      3 
      4 ig_service = IGService(config.username, config.password, config.api_key, config.acc_type)
      5 ig_service.create_session()

~\AppData\Local\Programs\Python\Python37\lib\site-packages\trading_ig\__init__.py in <module>
     23 )
     24 
---> 25 from .rest import IGService
     26 from .stream import IGStreamService
     27 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\trading_ig\rest.py in <module>
     24 from datetime import timedelta, datetime
     25 from .utils import _HAS_PANDAS, _HAS_MUNCH
---> 26 from .utils import conv_resol, conv_datetime, conv_to_ms, DATE_FORMATS, munchify
     27 from tenacity import Retrying
     28 

ImportError: cannot import name 'munchify' from 'trading_ig.utils' (C:\Users\(myname)\AppData\Local\Programs\Python\Python37\lib\site-packages\trading_ig\utils.py)

**Comment by wailam2323** [comment] 2021-12-29 21:43
pip install munch

**Comment by robgagliano** [comment] 2021-12-30 04:47
It should be added as a required dependency, along with pandas and tenacity.

**Comment by bug-or-feature** [comment] 2022-01-01 22:36
pandas, munch and tenacity are [optional by design](https://trading-ig.readthedocs.io/en/latest/faq.html#optional-dependencies). The latest release (0.0.16) handles absence of the optional dependencies better, and has better documentation. closing this

**Closed by bug-or-feature** 2022-01-01 22:36 UTC
