### ISSUE TITLE
fetch_markets_by_epics() only returning info for last item in list

### ISSUE THREAD

**Issue by eg271** [ig-python/ig-markets-api-python-library#251] opened 2022-06-09 15:00 UTC

**Comment by bug-or-feature** [comment] 2022-08-23 10:10
@eg271 I can't reproduce this, closing. There is an integration test that runs every night that checks the fetch_markets_by_epics() function, and it executes successfully with more than one epic

If you're really sure there is a problem, please re-open the issue, and provide more details. There is some guidance on creating issues [here](https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem)

**Closed by bug-or-feature** 2022-08-23 10:10 UTC
