### ISSUE TITLE
Replace bunch by munch

### ISSUE THREAD

**Issue by cimourdain** [ig-python/ig-markets-api-python-library#98] opened 2019-04-07 19:57 UTC
Use Munch instead of Bunch

Bunch does not detect python version in python3_compat file. Bunch uses platform.version() instead of sys.version_info. As a result, the python version is set as 2 instead of 3 and generates the following error.
```
Traceback (most recent call last):
  File "api_test.py", line 1, in <module>
    from trading_ig import IGService
  File ".../site-packages/trading_ig/__init__.py", line 17, in <module>
    from .rest import IGService
  File ".../site-packages/trading_ig/rest.py", line 15, in <module>
    from .utils import (_HAS_PANDAS, _HAS_BUNCH)
  File ".../site-packages/trading_ig/utils.py", line 21, in <module>
    from infi.bunch import bunchify
  File ".../site-packages/infi/bunch/__init__.py", line 31, in <module>
    from .python3_compat import *
  File ".../site-packages/infi/bunch/python3_compat.py", line 20, in <module>
    iteritems = dict.iteritems
AttributeError: type object 'dict' has no attribute 'iteritems'
```

**Comment by femtotrader** [comment] 2019-04-08 04:49
Hi @cimourdain 

I'm sorry but I can't see where is `iteritems = dict.iteritems`
I'm currently using https://github.com/Infinidat/munch ( https://pypi.org/project/munch/ )
not https://pypi.org/project/infi.bunch/

Kind regards

**Comment by cimourdain** [comment] 2019-04-08 08:39
you're right...i don't understand how i got bunch...

I installed trading_ig module via pip

```
Collecting trading_ig
  Downloading https://files.pythonhosted.org/packages/c0/fb/8c0aea2ebddf3a60065c95d19829b597fa843f63b8465ea7c3b862c767f6/trading_ig-0.0.6-py2.py3-none-any.whl
...
Collecting infi.bunch (from trading_ig)
  Downloading https://files.pythonhosted.org/packages/cf/95/dc268b05012ddaf5e0e120bd59521f69a4dba2b6595541c12fbd2ad718d5/infi.bunch-2.0.0.tar.gz
...
```

**Comment by mplanes** [comment] 2019-04-29 10:01
Steps to reproduce:
```
mkdir temp
cd temp
virtualenv -p python3 venv
source venv/bin/activate
pip install trading_ig
python -c "import trading_ig"
```

**Comment by AndrewCarterUK** [comment] 2019-12-31 10:35
Try using `git+https://github.com/ig-python/ig-markets-api-python-library` in your requirements or pip install instead of `ig_python`.

It looks like the versions on this repository are messed up or the master branch has unreleased/untagged code.

**Comment by univ1307** [comment] 2020-04-04 07:40
Hi guys am a complete newbie. Can you tell me how to replace bunch with munch in Windows 10 please? thanks a lot

**Comment by mayuequn** [comment] 2020-05-17 17:11
> Use Munch instead of Bunch
> 
> Bunch does not detect python version in python3_compat file. Bunch uses platform.version() instead of sys.version_info. As a result, the python version is set as 2 instead of 3 and generates the following error.
> 
> ```
> Traceback (most recent call last):
>   File "api_test.py", line 1, in <module>
>     from trading_ig import IGService
>   File ".../site-packages/trading_ig/__init__.py", line 17, in <module>
>     from .rest import IGService
>   File ".../site-packages/trading_ig/rest.py", line 15, in <module>
>     from .utils import (_HAS_PANDAS, _HAS_BUNCH)
>   File ".../site-packages/trading_ig/utils.py", line 21, in <module>
>     from infi.bunch import bunchify
>   File ".../site-packages/infi/bunch/__init__.py", line 31, in <module>
>     from .python3_compat import *
>   File ".../site-packages/infi/bunch/python3_compat.py", line 20, in <module>
>     iteritems = dict.iteritems
> AttributeError: type object 'dict' has no attribute 'iteritems'
> ```

same issue here

**Comment by wookiesh** [comment] 2020-07-10 08:48
Got the same issue, removed and installed the git one using `❯ pipenv run pip install git+https://github.com/ig-python/ig-markets-api-python-library`, now I get `ModuleNotFoundError: No module named 'Crypto'`.

**Comment by oliverpolden** [comment] 2020-07-10 12:01
I had this issue and resolved it. I have cryptography and pycrypto installed. Not sure if you need both or if one depends on the other. I think it's pycrypto you need so: pip install pycrypto.

**Comment by szev77** [comment] 2020-07-11 22:14
`pip install pycrypto` fails on my end. After a bit of digging `pip install pycryptodome` seems to do the job: [https://stackoverflow.com/a/58077717](url)

**Comment by bug-or-feature** [comment] 2020-09-26 17:45
These dependency issues should be fixed by recent updates. Even better once #149 is done. 
Closing

**Closed by bug-or-feature** 2020-09-26 17:45 UTC
